In [2]:
import pandas as pd

In [30]:
data = {
    'Name' : ["Wasio" , "Nisar" , "Sherri"],
    'Age' : [19 , 20 , 19.5],
    'City' : ["Gambat" , "Mirpur" , "Khairpur"]
}
# print(type(data))
#A DataFrame is a 2-dimensional labeled data structure in pandas, similar to a spreadsheet or SQL table
'''
KEY CHARACTERSITCS
2D structure: Rows and columns like a table
Labeled axes: Both rows (index) and columns have names
Mixed data types: Different columns can have different data types (numbers, strings, dates, etc.)
Size-mutable: You can add/remove rows and columns
'''
df = pd.DataFrame(data)
df["Square_of_Ages"] = df["Age"]*2
print(df.head()) #First 5 rows
print(df[['Name', 'Age']]) # Multiple columns
# print(type(df))
print(df) #displayed in formated columns/rows form along with index

     Name   Age      City
0   Wasio  19.0    Gambat
1   Nisar  20.0    Mirpur
2  Sherri  19.5  Khairpur
     Name   Age
0   Wasio  19.0
1   Nisar  20.0
2  Sherri  19.5
     Name   Age      City
0   Wasio  19.0    Gambat
1   Nisar  20.0    Mirpur
2  Sherri  19.5  Khairpur

In [7]:
df1 = pd.read_csv("customers.csv")
print(df1.info()) #Give some information about our csv file

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 12 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Index              100000 non-null  int64
 1   Customer Id        100000 non-null  object
 2   First Name         100000 non-null  object
 3   Last Name          100000 non-null  object
 4   Company            100000 non-null  object
 5   City               100000 non-null  object
 6   Country            100000 non-null  object
 7   Phone 1            100000 non-null  object
 8   Phone 2            100000 non-null  object
 9   Email              100000 non-null  object
 10  Subscription Date  100000 non-null  object
 11  Website            100000 non-null  object
dtypes: int64(1), object(11)
memory usage: 9.2+ MB
None

In [34]:
print("DateTypes:\n" , df1.dtypes)
print("Shape :" , df1.shape)
print("Columns : " , df1.columns.to_list())

DateTypes:
 Index                 int64
Customer Id          object
First Name           object
Last Name            object
Company              object
City                 object
Country              object
Phone 1              object
Phone 2              object
Email                object
Subscription Date    object
Website              object
dtype: object
Shape : (100000, 12)
Columns :  ['Index', 'Customer Id', 'First Name', 'Last Name', 'Company', 'City', 'Country', 'Phone 1', 'Phone 2', 'Email', 'Subscription Date', 'Website']

In [25]:
print(df1.describe()) # Only works on numerical columns

               Index
count  100000.000000
mean    50000.500000
std     28867.657797
min         1.000000
25%     25000.750000
50%     50000.500000
75%     75000.250000
max    100000.000000

In [39]:
#INDEXING AND SLICING

In [42]:
data = {
    'Name' : ["Wasio" , "Nisar" , "Sherri" , "Sarmad" , "Hasaan"],
    'Age' : [19 , 20 , 19.5, 20 , 21],
    'City' : ["Gambat" , "Mirpur" , "Khairpur" , "Sukkur" , "Karachi"]
}
df2 = pd.DataFrame(data)
print(df2)

     Name   Age      City
0   Wasio  19.0    Gambat
1   Nisar  20.0    Mirpur
2  Sherri  19.5  Khairpur
3  Sarmad  20.0    Sukkur
4  Hasaan  21.0   Karachi

In [52]:
#.loc - location - Label based indexing (row ,  columns) 
# sub_loc = df2.loc[1:3 , 2:3] # Error bcz we can not use indexes for both but we can use for rows (0-1 - by default generated for rows)
sub_loc = df2.loc[1:3 , ["Name" , "City"]]
sub_loc
#here 1:3 indicates rows indexes 1 to 3 (3 is included) and 2nd Shows which columns you want (Labels)

     Name      City
1   Nisar    Mirpur
2  Sherri  Khairpur
3  Sarmad    Sukkur

In [58]:
#.iloc
# sub_iloc = df2.iloc[1:3 , ["Name" , "City"]] # error bcz iloc requires numeric indexers for both rows and columns
sub_iloc = df2.iloc[1:3 , 0:2] #Here last is excluded like 0 : 2, so 0 is included and 2 is excluded
sub_iloc

     Name   Age
1   Nisar  20.0
2  Sherri  19.5

In [72]:
'''
| Feature              | `loc`                  | `iloc`                       |
| -------------------- | ---------------------- | ---------------------------- |
| Access by            | Label (index name)     | Position (integer index)     |
| Uses                 | Index labels           | Row/column numbers           |
| End value in slicing | Included               | Excluded                     |

'''

''

In [73]:
#WE CAN DO SELECTION BASED ON BOOLEAN VALUES

In [66]:
values = df2['Age'] > 19.5
df3 = df2[values]
df3

     Name   Age     City
1   Nisar  20.0   Mirpur
3  Sarmad  20.0   Sukkur
4  Hasaan  21.0  Karachi

In [71]:
# WE CAN ALSO DO MODIFICATION on the basis of values - altough we can do it on the basis of index but for large data index count would be difficult
df2.loc[df2["Age"] == 20 , "City"] = "Nawabshah" # iska mtlb un records ki city nikalo jinki age 20 ha, or unki city ko ab "Nawabshah" kr lo
print(df2)

     Name   Age       City
0   Wasio  19.0     Gambat
1   Nisar  20.0  Nawabshah
2  Sherri  19.5   Khairpur
3  Sarmad  20.0  Nawabshah
4  Hasaan  21.0    Karachi
<class 'str'>
Nawabshah

In [102]:
#NOTE :  We can also use custom indexes
df = pd.DataFrame({
    "Name": ["Ali", "Sara", "Ahmed"],
    "Age": [20, 22, 21]
}, index=["a", "b", "c"])

print(df.loc['a' : 'c']) # Row Label = 'a'  to 'c' (included) & all columns
print(df.loc[['a' , 'b'] , "Name"]) # Row label = "a , b" & Column label = "Name"
print(df.iloc[0:3 , 0:2]) # Row Position = 0 to 3 (excluded) & column position = 0 to 2 (excluded)
print(df.iloc[1,0]) # Row position = 1 & Column position = 1

    Name  Age
a    Ali   20
b   Sara   22
c  Ahmed   21
a     Ali
b    Sara
Name: Name, dtype: object
    Name  Age
a    Ali   20
b   Sara   22
c  Ahmed   21
Sara