In [1]:
import numpy as np
import pandas as pd

In [11]:
data = pd.read_csv("Countries.csv")
data.head()

,country,country_long,currency,capital_city,region,continent,demonym,latitude,longitude,agricultural_land,...,population,women_parliament_seats_pct,rural_population,urban_population,press,democracy_score,democracy_type,median_age,political_leader,title
0,Afghanistan,Islamic State of Afghanistan,Afghan afghani,Kabul,Southern Asia,Asia,Afghan,33.0,65.0,383560.0,...,41128771,27.01610,30181937,10946834,2.14,2.97,Authoritarian,12.9,Ashraf Ghani,President
1,Albania,Republic of Albania,Albanian lek,Tirana,Southern Europe,Europe,Albanian,41.0,20.0,11655.5,...,2775634,35.71430,1004807,1770827,2.62,5.98,Hybrid regime,33.7,Edi Rama,Prime Minister
2,Algeria,People's Democratic Republic of Algeria,Algerian dinar,Algiers,Northern Africa,Africa,Algerian,28.0,3.0,413588.0,...,44903225,8.10811,11328186,33575039,1.71,3.50,Authoritarian,24.0,Abdelmadjid Tebboune,President
3,Andorra,Principality of Andorra,Euro,Andorra la Vella,Southern Europe,Europe,Andorran,42.5,1.5,187.2,...,79824,46.42860,9730,70094,3.17,0.00,Unknown,38.9,Xavier Espot Zamora,Head of Government
4,Angola,People's Republic of Angola,Angolan kwanza,Luanda,Middle Africa,Africa,Angolan,-12.5,18.5,569525.0,...,35588987,33.63640,11359649,24229338,2.24,3.62,Authoritarian,12.4,João Lourenço,President

**Q1. Which Country has highest population**

In [81]:
# data.isna().sum()
data[data["population"] == data["population"].max()]["country"]

75    India
Name: country, dtype: object

**Q2. What is the Capital of country having highest population**

In [17]:
data[data["population"] == data["population"].max()]["capital_city"]

75    New Delhi
Name: capital_city, dtype: object

**Q3. Which country has least Population**

In [82]:
data[data["population"] == data["population"].min()]["country"]

179    Tuvalu
Name: country, dtype: object

**Q4. What is the Capital of country having least population**

In [20]:
data[data["population"] == data["population"].min()]["capital_city"]

179    Funafuti
Name: capital_city, dtype: object

**Q. Give me 5 countries with highest democartic score**

In [83]:
data.nlargest(5 , "democracy_score")[["country" , "democracy_score"]]

#WE can use sorting also

value = data.sort_values(by ="democracy_score" , ascending= False) # it will not affect actual data unless i use 'inplace' or equals to orignal column
value["country"].head()

127         Norway
74         Iceland
164         Sweden
122    New Zealand
46         Denmark
Name: country, dtype: object

**Q. How many total regions are**

In [86]:
# count = data["region"].count() --> It is wrong bcz it just give row count not count based on region
count = data["region"].value_counts().count() # value count tells us individual count based on each region, count will tell total region count
print(count)

22

**Q. How many countries lie in Eastern Euopriean region**

In [90]:
count = data[data["region"] == "Eastern Europe"]["country"].count()
# Alternative Approach
count = data["region"].value_counts()["Eastern Europe"]
print(count)

10

**Q. Who is the political leader of 2nd highest populated country**

In [99]:
data.nlargest(2 , "population")[["country" , "political_leader"]].iloc[1] #Index based selection bcz two largest values are extracted one is on 0th index and 2nd is on 1st 

#Alternative
data[data["population"] == data["population"].nlargest(2).iloc[1]][["political_leader"]]

   political_leader
34       Xi Jinping

**Q. How many countries whose political leaders are unknown**

In [53]:
count = data[data["political_leader"].isna()]["country"].count()
print(count)

7

**Q. How many countries have Republic in their full name**

In [69]:
# count = data[data["country_long"].]["country"].count()
# print(count)
count = 0
def count_names(text):
    global count
    if "Republic" in text:
        count += 1
data["country_long"].apply(count_names)
print(count)

125

In [71]:
#Alternative and Better approach
count = data["country_long"].str.contains("Republic").sum()
print(count)

125

**Q. Which country in Africa region has highest population**

In [105]:
value = data[data["continent"] == "Africa"]
value[value["population"] == value["population"].max()]["country"]

125    Nigeria
Name: country, dtype: object