In [48]:
import pandas as pd

In [49]:
#Now we can read csv file (comma seperated value format) in which by default seperator is comma ','
df = pd.read_csv("products.csv") # this function requires 'FILE FORMATED DATA'
# now products.csv is a file fomrated data but what about we have String and we have to convert into csv file so first we have to convert it into
# file formated data
df.head()
df.tail()

,Index,Name,Description,Brand,Category,Price,Currency,Stock,EAN,Color,Size,Availability,Internal ID
995,996,Silent Router Phone Portable Automatic,Piece the fight near never once bank.,Huffman Group,Toys & Games,903,USD,737,8227581307423,MediumAquaMarine,XL,limited_stock,33
996,997,Digital Treadmill Clean Go,Apply drive outside reach apply.,Woodward Group,Toys & Games,8,USD,330,522633507294,PaleVioletRed,Medium,out_of_stock,9
997,998,Wireless Vacuum Shaver,Line cup course student each about.,Ramos-Cardenas,Beauty & Personal Care,615,USD,630,1892829625606,PaleVioletRed,Extra Large,pre_order,4
998,999,Portable Cooker Brush 360 Digital Mini,History feel worry painting only power bad.,Hooper-Bender,Men's Clothing,811,USD,566,1683591150065,LightGreen,S,in_stock,65
999,1000,Smart Watch Edge Digital Sense,Pay image either rest.,Campos Inc,Kitchen Appliances,867,USD,769,8697154897673,Gainsboro,50x70 cm,limited_stock,10

In [50]:
#for this conversion we have to use STRINGIO
from io import StringIO

In [51]:
data = ('Name , Age , City\n'
       'Wasio , 19 , Gambat\n' 
       'Nisar , 20 , Mirpur\n'
       'Hasaan , 21 , Khairpur\n')
# Above is the actual format of CSV file
type(data)
#now i have to convert this str into file formarted data basically term used for StringIO -> in memory file format object 
df = pd.read_csv(StringIO(data))
df

     Name    Age        City
0   Wasio      19     Gambat
1   Nisar      20     Mirpur
2  Hasaan      21   Khairpur

**Reading Specific columns**

In [33]:
df = pd.read_csv("products.csv" , usecols= ['Name', 'Brand' , 'Price' , 'Size'])
# We can convert this sub dataset into csv file back using 'to_csv' function
df.to_csv('fileName.csv' , index= False) # False means it does not store the indexes now
df.head()

,Name,Brand,Price,Size
0,Thermostat Drone Heater,Bradford-Yu,74,Medium
1,Ultra Speaker Iron Grill Advanced One,Douglas Group,510,Small
2,Watch Headphones Kettle,Landry-Austin,254,XXL
3,Portable Toaster Clock Monitor Silent,"Odom, Norton and Foster",69,XL
4,Pro Toaster Oven,"Fowler, Mendoza and Mcdaniel",525,XL

In [66]:
numbers = ('a , b , c , d\n'
          '1,2,3,4\n'
          '3,4,5,6\n'
          '8,9,0')
df = pd.read_csv(StringIO(numbers))
df
print(df.dtypes) # last column has null value so Pandas take by  default as NaN (is float) so entire column become float 
#BUT we can specify the datatype intially at the time of file reading

# df2 = pd.read_csv(StringIO(numbers), dtype= 'int')  # Got error bcz it contain NaN value
df2 = pd.read_csv(StringIO(numbers), dtype= 'float')
df2.dtypes
df2.info() #clearly shows column 4 contain 2 not null values means 1 null values is present also
df2 # all are converted into Float values

a        int64
 b       int64
 c       int64
 d     float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      float64
 1    b      3 non-null      float64
 2    c      3 non-null      float64
 3    d      2 non-null      float64
dtypes: float64(4)
memory usage: 228.0 bytes

    a    b    c     d
0  1.0  2.0  3.0  4.0
1  3.0  4.0  5.0  6.0
2  8.0  9.0  0.0  NaN

In [69]:
 # We can also see null values using 'is_null' function
print(df2.isnull())
print(df2.isnull().sum())

      a      b      c       d
0  False  False  False  False
1  False  False  False  False
2  False  False  False   True
a      0
 b     0
 c     0
 d     1
dtype: int64

***Custom DataTypes***

In [79]:
numbers = ('a,b,c,d\n'
          '1,2,3,4\n'
          '3,4,5,6\n'
          '8,9,0')
df = pd.read_csv(StringIO(numbers) , dtype= {'a': int , 'b' : object , 'c' : int})
df.dtypes
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       3 non-null      int64
 1   b       3 non-null      object
 2   c       3 non-null      int64
 3   d       2 non-null      float64
dtypes: float64(1), int64(2), object(1)
memory usage: 228.0+ bytes

***CUSTOM INDEXES***

In [87]:
data = ('Index,Name,Age,City\n'
       '2,Wasio , 19 , Gambat\n' 
       '3,Nisar , 20 , Mirpur\n'
       '6,Hasaan , 21 , Khairpur\n')
#Here we want to use 'Index' column as Index not by default index (0-n)
df = pd.read_csv(StringIO(data) , index_col=0) # 0 is number of column either 1st , 2nd or zeroth
df2 = pd.read_csv(StringIO(data) , usecols=['Name' , 'Age'] , index_col=0) #here index is 0th column
#NOTE : Now Pandas looks at the first remaining column (position 0), which is Name, and makes it the index.
print(df2)

# If you wanted Index as the index Then you must include it in usecols:
df2 = pd.read_csv(StringIO(data), usecols=['Index', 'Name', 'Age'], index_col=0)
print(df2)

# index_col=0 means:
# Use the first column after all column selections (usecols) have been applied, not necessarily the first column in the original CSV.

         Age
Name
Wasio     19
Nisar     20
Hasaan    21
          Name  Age
Index
2       Wasio    19
3       Nisar    20
6      Hasaan    21