In [11]:
import numpy as np
import pandas as pd

In [12]:
#SAMPLE DATA
data = {
    'Date':     pd.date_range('2024-01-01', periods=30),
    'City':     np.random.choice(['Karachi', 'Lahore', 'Islamabad', 'Quetta', 'Peshawar'], 30),
    'Product':  np.random.choice(['Tea', 'Rice', 'Sugar', 'Flour', 'Oil'], 30),
    'Category': np.random.choice(['Grocery', 'Beverage', 'Staple'], 30),
    'Sales':    np.random.randint(100, 1000, 30),
    'Units':    np.random.randint(1, 50, 30),
    'Rep':      np.random.choice(['Ali', 'Sara', 'John', 'Nadia', 'Usman'], 30),
    'Returned': np.random.choice([True, False], 30, p=[0.1, 0.9]),
}

df = pd.DataFrame(data)
df

         Date       City Product  Category  Sales  Units    Rep  Returned
0  2024-01-01     Quetta     Tea   Grocery    514      5   Sara     False
1  2024-01-02    Karachi     Oil    Staple    467      8    Ali     False
2  2024-01-03   Peshawar   Sugar   Grocery    152     45   Sara     False
3  2024-01-04    Karachi   Flour    Staple    360     38   Sara     False
4  2024-01-05     Quetta     Tea    Staple    855     49  Nadia     False
5  2024-01-06  Islamabad     Tea   Grocery    493     35  Nadia      True
6  2024-01-07    Karachi   Flour   Grocery    458     12   John      True
7  2024-01-08    Karachi     Tea  Beverage    158     17  Usman     False
8  2024-01-09  Islamabad   Sugar  Beverage    451     27    Ali     False
9  2024-01-10   Peshawar    Rice  Beverage    631      4  Nadia     False
10 2024-01-11  Islamabad    Rice    Staple    960     22  Usman     False
11 2024-01-12  Islamabad     Oil   Grocery    796      8   John     False
12 2024-01-13     Lahore   Flour   Grocery    974      4    Ali     False
13 2024-01-14     Lahore    Rice   Grocery    446     22  Usman     False
14 2024-01-15   Peshawar     Oil   Grocery    445     23   John     False
15 2024-01-16     Quetta     Tea   Grocery    282     27    Ali     False
16 2024-01-17     Quetta   Flour    Staple    713     31  Nadia     False
17 2024-01-18  Islamabad   Sugar   Grocery    745     35  Nadia      True
18 2024-01-19     Quetta     Tea  Beverage    701     27   Sara     False
19 2024-01-20    Karachi   Sugar  Beverage    369     11  Usman     False
20 2024-01-21   Peshawar     Tea    Staple    967      5   John     False
21 2024-01-22   Peshawar     Tea    Staple    250     32    Ali     False
22 2024-01-23    Karachi     Tea    Staple    360     33   John     False
23 2024-01-24     Quetta   Flour   Grocery    859     40  Usman     False
24 2024-01-25     Quetta    Rice   Grocery    798      6  Usman     False
25 2024-01-26     Lahore   Flour   Grocery    923     33  Usman     False
26 2024-01-27     Quetta   Sugar    Staple    477     46  Nadia      True
27 2024-01-28   Peshawar   Flour  Beverage    327     21  Nadia     False
28 2024-01-29  Islamabad    Rice    Staple    316     16  Usman      True
29 2024-01-30  Islamabad   Flour   Grocery    863     24   John     False

In [21]:
'''
why we use pivot tables in pandas?
Pivot tables are used to summarize and reorganize large data into a meaningful format — 
instead of staring at hundreds of raw rows, you get a clean summary in seconds.
'''
pf = pd.pivot_table(df , index="City" , columns="Product" , values="Sales") # You should have to mention these values to get meaningful data
pf
# data -> Dataframe 'df'
# index -> City 
# columns -> Product
# values -> Sales (Use Numeric values bcz of aggregation)
#Now some Sales values are NaN it is because 'Some Cities has not any product Sale like Karachi has no any sale of Rice - also in actual data'
#NOTE : Below values is not actual value, it is the mean of all each column like -> Isb ma Rice ki Sales ha 960 and 316 so 638 is the mean of both 
# MEAN is set as by default, but we can change it 
pf = pd.pivot_table(df , index="City" , columns="Product" , values="Sales" , aggfunc='sum')
pf

pf = pd.pivot_table(df , index="City" , columns="Product" , values= ["Sales" , "Units"] , aggfunc='sum') #Can use multiple values (Numeric, nhi to error)
pf

            Sales                                Units                    \
Product     Flour    Oil    Rice   Sugar     Tea Flour   Oil  Rice Sugar
City
Islamabad   863.0  796.0  1276.0  1196.0   493.0  24.0   8.0  38.0  62.0
Karachi     818.0  467.0     NaN   369.0   518.0  50.0   8.0   NaN  11.0
Lahore     1897.0    NaN   446.0     NaN     NaN  37.0   NaN  22.0   NaN
Peshawar    327.0  445.0   631.0   152.0  1217.0  21.0  23.0   4.0  45.0
Quetta     1572.0    NaN   798.0   477.0  2352.0  71.0   NaN   6.0  46.0


Product      Tea
City
Islamabad   35.0
Karachi     50.0
Lahore       NaN
Peshawar    37.0
Quetta     108.0

CROSS TABLES (used for just counting purpose) while Pivot tables for Aggregation work
Crosstab() is used to create a frequency table (count table) between two or more categorical variables.
# Think like : How many records belong to each combination of categories
# Its Syntax is different from pivot tables bcz pivot requires 
- values → what to aggregate
- index → rows
- columns → columns
- aggfunc → aggregation function

but Cross Tab just
- First argument → rows
- Second argument → columns

In [25]:
ct = pd.crosstab(df["City"], df["Product"])
ct
# In a normal crosstab(), 
# there is no values parameter involved because Pandas is simply counting rows.

Product    Flour  Oil  Rice  Sugar  Tea
City
Islamabad      1    1     2      2    1
Karachi        2    1     0      1    2
Lahore         2    0     1      0    0
Peshawar       1    1     1      1    2
Quetta         2    0     1      1    4